bigint uploaded
garipovroma/first-term pull request #2
Opened 2020-06-29 21:17 UTC by garipovroma

2020-07-01 22:45 UTC, kt-cpp requested changes
Комментарии помеченные [note] к исправлению не обязательны.

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.h
>  #include <gmp.h>
[minor] Тебе правда нужен этот `include`?

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.h
> +    friend std::vector<uint32_t> multiply(const std::vector<uint32_t> &a, const std::vector<uint32_t> &b);
[minor] Этот метод выглядит так, как будто он должен быть приватным

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer() {
[semantic] Лучше делать member initialization

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    long long x = a;
[style] `long long` не имеет точного размера

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this = -(*this);
[semantic] Какие-то странные фокусы с переприсваиванием в конструкторе, выглядит как ub

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t to_delete = (sign ? 0 : UINT32_MAX);
[style] Константа `UINT32_MAX` используется во многих местах, имеет смысл вынести её в статическую переменную

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        mas.push_back(to_fill);
[performance] Последовательные `push_back` вызовут много ненужных переаллокаций

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (str.empty()) {
[semantic] Разве пустая строка -- это число? Пересмотри этот метод в целом на предмет корректности и возможных строк, которые он может попарсить.

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    int loop_beg = (str[0] == '-' ? 1 : 0);
[minor] Бывает также и префиксный `+`

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this = -(*this);
[guarantees] Здесь и далее в методах есть проблемы с исключениями и гарантиями. Там, где это возможно, нужно предоставлять максимальную степень гарантий. Большинство подобных проблем решаются через swap trick

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        big_integer cur = x % ten;
[minor] Здесь можно явно вызывать деление на короткое число, минуя тяжёлую версию для деления длинных чисел

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            digit = cur.sign ? 0 : UINT32_MAX;
[minor] `cur.sign` бывает `false`?

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer res;
[minor] Выглядит как конструктор копирования

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        res.mas[i] = (mas[i] ^ UINT32_MAX);
[minor] В этом методе куда органичнее смотрелось бы побитовое отрицание, а не ^

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    x.shrink_to_fit();
[minor] `x` и `y` бывают не сжатыми?

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    std::reverse(x.mas.begin(), x.mas.end());
[performance] `reverse` совершает много ненужных копирований чисел, здесь можно обойтись циклом ниже. Кстати, не стоит оставлять закомментированный код без причины.

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this = 0;
[minor, style] Эта и следующая строчка могут быть склеены в одну.

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        new_mas = (sign ? multiply(mas, (-rhs).mas) : multiply((-(*this)).mas, rhs.mas));
[style] Тернарник выглядит сложно, раскрой его, пожалуйста.

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer a = (sign ? *this : -(*this));
[style] Явно не хватает функции `abs()`

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer big_integer::div(uint32_t b) {
[guarantees] `b == 0`?

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        big_integer bx;
[note, style] Почему бы не определить эту переменную непосредственно перед использованием?

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            __uint128_t trial = (x ^ (w << 32u) ^ (v << 64u)) / ((y << 32u) ^ z);
[note, style] На мой взгляд, ксор это слишком сложная функция, чтоб в уме представлять что она делает. Здесь бы лучше подошли `|` или `+`

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        if (b.mas.size() == 1) {
[style] Эту проверку лучше сделать первой. Также стоит убрать вложенность ифов конструкцией `else if`, код станет понятнее

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator&=(big_integer const& rhs) {
[style] Три следующих операции очень похожи между собой.
Вынеси общий код, используя лямбды или указатели на функцию.

2020-07-01 22:45 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        (*this) *= TWO;
[performance] Сдвиги могут быть реализованы намного эффективнее, чем последовательное умножение.

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.h
>  #include <gmp.h>
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.h
> +    friend std::vector<uint32_t> multiply(const std::vector<uint32_t> &a, const std::vector<uint32_t> &b);
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +big_integer::big_integer() {
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    long long x = a;
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    uint32_t to_delete = (sign ? 0 : UINT32_MAX);
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    if (str.empty()) {
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    int loop_beg = (str[0] == '-' ? 1 : 0);
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +        *this = -(*this);
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +            digit = cur.sign ? 0 : UINT32_MAX;
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +        res.mas[i] = (mas[i] ^ UINT32_MAX);
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    std::reverse(x.mas.begin(), x.mas.end());
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    x.shrink_to_fit();
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +        *this = 0;
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +        new_mas = (sign ? multiply(mas, (-rhs).mas) : multiply((-(*this)).mas, rhs.mas));
fixed

2020-07-05 22:59 UTC, garipovroma commented on bigint/big_integer.cpp
> +    big_integer a = (sign ? *this : -(*this));
fixed

2020-07-05 23:00 UTC, garipovroma commented on bigint/big_integer.cpp
> +big_integer big_integer::div(uint32_t b) {
fixed

2020-07-05 23:00 UTC, garipovroma commented on bigint/big_integer.cpp
> +        big_integer bx;
fixed

2020-07-05 23:00 UTC, garipovroma commented on bigint/big_integer.cpp
> +        if (b.mas.size() == 1) {
fixed

2020-07-05 23:00 UTC, garipovroma commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator&=(big_integer const& rhs) {
fixed

2020-07-05 23:00 UTC, garipovroma commented on bigint/big_integer.cpp
> +        (*this) *= TWO;
fixed

2020-07-06 00:35 UTC, kt-cpp commented
1) Подтяни свежие тесты из upstream в свой master
2) Отребейзь свою ветку bigint относительно своего мастера, чтоб не было конфликтов при мёрже и в списке изменений не было вектора

2020-07-06 01:05 UTC, kt-cpp commented on bigint/big_integer.h
>  #include <gmp.h>
точно?)

2020-07-06 01:08 UTC, garipovroma commented on bigint/big_integer.h
>  #include <gmp.h>
действительно, приношу извинения за дизинформацию

2020-07-06 01:08 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer() {
Не везде пофикшено, конструктор копирования остался старым

2020-07-06 01:32 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer big_integer::div(uint32_t b) {
точно?)

2020-07-06 01:50 UTC, kt-cpp requested changes

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = (x > 0);
[minor] Давай поаккуратнее с переменными

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        x = x ^ (MAX_DIGIT + 1ull);
[semantic, minor] Зачем этот ксор?

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t to_delete = (sign ? 0 : MAX_DIGIT);
[minor, style] Имеет смысл сделать отдельную функцию для этой операции

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer y = b;
[performance, minor] Зачем эти копии?

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (int32_t i = x.mas.size() - 1; i >= 0; i--) {
[semantic, minor] size_t

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
[style, minor] `resize` позволяет передать элемент, которым собираемся заполнять

2020-07-06 01:50 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    std::reverse(cur.mas.begin(), cur.mas.end());
[performance, minor] Зачем реверсы, если можно сразу стереть из начала?

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.h
>  #include <gmp.h>
теперь точно fixed)

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +big_integer::big_integer() {
исправил

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +    sign = (x > 0);
fixed

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +        x = x ^ (MAX_DIGIT + 1ull);
fixed

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +    uint32_t to_delete = (sign ? 0 : MAX_DIGIT);
fixed

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +    big_integer y = b;
fixed

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +    for (int32_t i = x.mas.size() - 1; i >= 0; i--) {
fixed

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +    }
fixed

2020-07-06 10:52 UTC, garipovroma commented on bigint/big_integer.cpp
> +    std::reverse(cur.mas.begin(), cur.mas.end());
fixed

2020-07-06 12:08 UTC, kt-cpp commented
Один комментарий остался :(

2020-07-06 12:39 UTC, kt-cpp approved these changes

2020-07-06 12:39 UTC, merged